### PR TITLE
Create sortable.php

### PR DESCRIPTION
**Pull request by AlainRnet**
There are 2 ways to do this: 
1. use a different template template for the module (this new added file)
2. add an option (in the XML file) to add the call to the JS file and add the sortable classes to the table and headers

### CODE REVIEW

**Comment by Gileba** [comment]
I have a preference for option 2 and will change the PR accordingly. Thanks for resubmitting this, @AlainRnet

**Comment by Gileba** [comment]
@AlainRnet The JS seems to be missing, could you send it to me by mail? You can add the French translations in that mail as well. I will add it to this PR then.

**Comment by Gileba** [comment]
@AlainRnet Thanks for the JS-files. The new strings are

- MOD_TABLEMAKERCSV_SORTABLE_LABEL="Sortable"
- MOD_TABLEMAKERCSV_SORTABLE_DESC="Allow the visitor to sort the table"

**Comment by AlainRnet** [comment]
Thank you, I didn't see it. Here you are :

  * MOD_TABLEMAKERCSV_SORTABLE_LABEL="Activer le tri"
  * MOD_TABLEMAKERCSV_SORTABLE_DESC="Permettre aux visiteurs de trier la
    table"



Le 27.04.23 à 23:41, Gijs Lamon a écrit :

**Pull request merged**
