### PR TITLE
Correct CSS syntax for module suffixes

### LINKED ISSUE #92: Variable modulesclass_sfx can't be used for defining CSS styles in view
(reported by @AlainRnet in PR #91)

In case of adding one or more classes to the module, there is no . in front of the extra classes and these are not correctly written in the style definition. This results in an error and affected styles are not applied.

### PR DESCRIPTION
**Pull request by Gileba**
Fixes #92
Replacement for #91 
Replacement for #93

### CODE REVIEW

**Comment by Gileba** [comment]
@AlainRnet : Can you try this code out?

[mod_tablemakerforcsv-css-module-suffix-syntax.zip](https://github.com/Gileba-org/mod_tablemakerforcsv/files/11721289/mod_tablemakerforcsv-css-module-suffix-syntax.zip)

**Comment by AlainRnet** [comment]
I think $ miss on line 38 in /src/tmpl/default.php
I see your function, it's fine.

**Comment by Gileba** [comment]
> I think $ miss on line 38 in /src/tmpl/default.php I see your function, it's fine.

Thanks for the feedback, that last thing is fixed as well. I'll release an update later today.

**Comment by AlainRnet** [comment]
I think you know it : there 012 above search field when I test the zip file above ([mod_tablemakerforcsv-css-module-suffix-syntax.zip](https://github.com/Gileba-org/mod_tablemakerforcsv/files/11721289/mod_tablemakerforcsv-css-module-suffix-syntax.zip))

**Comment by Gileba** [comment]
> I think you know it : there 012 above search field when I test the zip file above ([mod_tablemakerforcsv-css-module-suffix-syntax.zip](https://github.com/Gileba-org/mod_tablemakerforcsv/files/11721289/mod_tablemakerforcsv-css-module-suffix-syntax.zip))

I knew that, yes. That's solved already in a previous code update after I uploaded the zip

**Pull request merged**
